config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'header/show'
  end
  get 'notifications/index'
  # 顧客用
  # url/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理用
  # url/admin/sign_up
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"

  }

    root to: "user/homes#top"
    post 'user/homes/guest_sign_in', to: 'user/homes#guest_sign_in'
    scope module: :user do
    get "home/about" => "homes#about" , as: "about"
    get '/user/genre/search/:id', to: '/user/searches#genre_search', as: 'user_genre_search'
    get '/search', to: 'searches#search', as: 'search'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch '/users/withdraw' => 'users#withdraw'
    resources :notifications, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get "users/:id/favorite" => "users#favorites",as: 'favorites_community'
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :communities, only: [:index, :show] do
    resources :post_boards, only: [:index, :create,:edit,:update,:destroy] 
    resource  :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :communities, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :post_boards, only: [:index, :destroy]
      
    end
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post_board.rb
class PostBoard < ApplicationRecord
  belongs_to :community
  belongs_to :user
  
  
  validates :body, presence: true
  
  POST_BOARD = "Post_board"

  def self.search_for(content, method) #条件にbody(コメント内容)も検索出来る
  case method
  when "body"
    joins(:user).where('body LIKE ?', '%' + content.to_s)
  else
    joins(:user).where('body LIKE ?', '%' + (content || '').to_s + '%')
  end
  end
end

app/controllers/admin/post_boards_controller.rb
class Admin::PostBoardsController < ApplicationController
  def index
    @community = Community.find(params[:community_id])
    @post_boards = @community.post_boards.order('created_at DESC').page(params[:page]).per(3)
    @users = User.all
  end

  def destroy
    @post_board = PostBoard.find(params[:id])
    @community = @post_board.community
    @post_board.destroy
    redirect_to admin_community_post_boards_path(community_id: @community.id)
  end
end

app/controllers/user/post_boards_controller.rb
class User::PostBoardsController < ApplicationController

  def index
    @community = Community.find(params[:community_id]) #@community`という変数に、`params[:community_id]`に対応する`Community`（コミュニティ）をデータベースから取得
    @post_board = PostBoard.new                        #PostBoard`（掲示板）のインスタンスを作成
    @post_boards = @community.post_boards
    @users = User.all
    @sort = params[:sort] #@sort`の値によって条件分岐
  if @sort == "newest"
    @post_boards = @post_boards.order(created_at: :desc) #@sort`が "newest" と等しい場合、`@post_boards`を`created_at`の降順でソート
  elsif @sort == "oldest"
    @post_boards = @post_boards.order(created_at: :asc) #@sort`が "oldest" と等しい場合、`@post_boards`を`created_at`の昇順でソート
  else
    @post_boards = @community.post_boards.order(created_at: :desc) #特定のコミュニティに関連する掲示板データを取得し、ソートの条件に従って並び替え
  end
  
  @users = User.all

  # 追加コード
  @users = @post_boards.map(&:user).uniq #@post_boards`は特定のコミュニティに関連する掲示板データのリストを表しています。そして、`map`メソッドを使って、`@post_boards`の各要素（つまり各掲示板）に対して以下の処理を実行
  end                                    #&:user`は、各掲示板の`user`というメソッドを呼び出すための短縮記法です。つまり、各掲示板のユーザーを取得
                                         #uniq`メソッドを使って、ユーザーリストから重複したユーザーを除去しています。これにより、`@users`には`@post_boards`に関連するユーザーの一意なリストが代入
  def create
    @community = Community.find(params[:community_id]) # 選択したコミュニティを取得
    @post_boards = @community.post_boards
    @post_board = @community.post_boards.build(post_board_params) #buildメソッド　アソシエーションを使用して、モデルから取得し新しいオブジェクトを作成
    @post_board.user_id = current_user.id
    if @post_board.save
      flash[:notice] = "成功しました。"
      redirect_to community_post_boards_path(@community)
    else
      flash[:alert] = "登録に失敗しました。"
      render :index
    end
  end

    def destoroy
       @post_board = PostBoards.find(params[:id]) # 削除する投稿を取得
    if @post_boad.user_id == current_user.id # ログインユーザーと投稿のユーザーが一致しているかチェック
       @post_board.destroy #投稿削除
    end
       flash[:notice] = "削除しました。"
       redirect_to community_post_boards_path(params[:community_id]) # コミュニティの投稿一覧ページにリダイレクト
    end

    private

    def post_board_params
      params.require(:post_board).permit(:user_id, :community_id, :body,:favorite_id)
    end
end

app/helpers/admin/post_boards_helper.rb
module Admin::PostBoardsHelper
end

app/helpers/user/post_boards_helper.rb
module User::PostBoardsHelper
end

app/views/admin/post_boards/index.html.erb
<div class="container mt-5">
  <h3><%= @community.name %>の投稿一覧</h3>
    <table class="table mt-3">
     <tr>
      <th>アイコン</th>
      <th>名前</th>
      <th>投稿</th>
      <th>日時</th>
      <th></th>
       <%= link_to "投稿ページへ", admin_communities_path(@user), class: "btn btn-primary" %>
        </tr>
        <% @post_boards.each do |post_board| %>
         <tr>
           <td><%= image_tag post_board.user.get_profile_image(60, 60), class: "rounded-circle mx-auto d-block" %></td>
          <td><%= link_to post_board.user.name, admin_user_path(post_board.user.id) %></td>
           <td><%= post_board.body %></td>
            <td><%= post_board.created_at.strftime("%Y年%m月%M日 %H時%M分") %></td>
             <td>
              <%= link_to '削除', admin_community_post_board_path(post_board.community_id, post_board), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
               </td>
                </tr>
                <% end %>
               </table>
              <div class="post_board_paginate">
             <%= paginate @post_boards %>
            </div>
          </div>
         <head>
       <style>
       
  body {
    background-color: #FFFFF0; /* 背景色の指定 */
  }

.post_board_paginate{
  width: 100%;
  margin: auto;
}

/* ページネーション全体 */
.pagination{
  text-align: center;
  display: flex;
  justify-content: center;
}

/* ページネーションのspan */
.pagination span{
  text-align: center;
  width: 50px;
  font-size: 20px;
}

/* ページネーションのリンク文字（a） */
.pagination a{
  color: #818181;
  display: block;
  width: 100%;
  height: 100%;
  font-weight: bold;
  padding: 10px;
}

/* ページネーションの文字にカーソルを載せた時 */
.pagination a:hover{
  width: 50px;
  height: 50px;
  background-color: #84b8eb;
  color: #FFF;
  border-radius: 100%;
  padding: 10px;
}

/* 現在のページの数字についての表記 */
.current{
  font-weight: bold;
  color: #84b8eb;
  padding: 10px;
}
  </style>