config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'header/show'
  end
  get 'notifications/index'
  # 顧客用
  # url/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理用
  # url/admin/sign_up
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"

  }

    root to: "user/homes#top"
    post 'user/homes/guest_sign_in', to: 'user/homes#guest_sign_in'
    scope module: :user do
    get "home/about" => "homes#about" , as: "about"
    get '/user/genre/search/:id', to: '/user/searches#genre_search', as: 'user_genre_search'
    get '/search', to: 'searches#search', as: 'search'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch '/users/withdraw' => 'users#withdraw'
    resources :notifications, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get "users/:id/favorite" => "users#favorites",as: 'favorites_community'
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :communities, only: [:index, :show] do
    resources :post_boards, only: [:index, :create,:edit,:update,:destroy] 
    resource  :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :communities, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :post_boards, only: [:index, :destroy]
      
    end
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_action :authenticate_admin!

  def index
   @users = User.all.page(params[:page]).per(7)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :email, :is_active)
  end
end

app/controllers/user/communities_controller.rb
class User::CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end
  
  def show
    @community = Community.find(params[:id])
    @communities = Community.all
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
  @community = Community.find(params[:community_id])
  favorites = current_user.favorites.new(community_id: @community.id)
  favorites.save
  end

  def destroy
  @community = Community.find(params[:community_id])
  favorites = current_user.favorites.find_by(community_id: @community.id)
  favorites.destroy
  end
end

app/controllers/user/header_controller.rb
class User::HeaderController < ApplicationController
  def show
  @unread_notifications_count = Notification.where(read: false).count
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @community = Community.all.order('created_at DESC').page(params[:page]).per(3)
  end
  
  def guest_sign_in
    @user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.skip_confirmation!  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
    sign_in @user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def about
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!

def create
  if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @room = @message.room
    if @message.save
      # 追加の為一旦コメントアウト redirect_to user_room_path(@message.room)
      @roommembernotme = Entry.where(room_id: @room.id).where.not(user_id: current_user.id) #@roommembernotme`という変数に、`Entry`モデルからデータを取得
      @theid = @roommembernotme.find_by(room_id: @room.id)  #条件は、`room_id`が`@room.id`でありかつ`user_id`が現在のユーザーのID (`current_user.id`) ではないこと
      notification = current_user.active_notifications.new( #@theid`という変数に、`@roommembernotme`の中からさらに条件を指定してデータを取得しています。この条件は、`room_id`が`@room.id`であること
        room_id: @room.id,                                  #notification`という変数に、現在のユーザー (`current_user`) のアクティブな通知を作成しています。この通知には、以下の情報が含まれる
        message_id: @message.id,
        visited_id: @theid.user_id,
        visitor_id: current_user.id,
        action: 'dm'
      )
      # 特定の条件を持つデータを取得し、それを利用して通知を作成
      # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
      

      redirect_to room_path(@message.room)
    end
  else
    redirect_back(fallback_location: root_path)
  end
end
  private

    def message_params
      params.require(:message).permit(:user_id,:room_id, :body).merge(user_id: current_user)
    end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  
  #@notifications変数に、現在のユーザー `current_user` の受動的な（受け取った）通知を取得
  #@notificationsの中から`checked`が`false`（未確認）の通知を選択し、それぞれの通知に対しの処理
  #notification.update(checked: true)`：選択された通知の`checked`を`true`（確認済み）に更新
  
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(5)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
    
  def destroy
    @notifications = current_user.notifications.destroy_all
    redirect_to notifications_path
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_boards_controller.rb
class User::PostBoardsController < ApplicationController

  def index
    @community = Community.find(params[:community_id]) #@community`という変数に、`params[:community_id]`に対応する`Community`（コミュニティ）をデータベースから取得
    @post_board = PostBoard.new                        #PostBoard`（掲示板）のインスタンスを作成
    @post_boards = @community.post_boards
    @users = User.all
    @sort = params[:sort] #@sort`の値によって条件分岐
  if @sort == "newest"
    @post_boards = @post_boards.order(created_at: :desc) #@sort`が "newest" と等しい場合、`@post_boards`を`created_at`の降順でソート
  elsif @sort == "oldest"
    @post_boards = @post_boards.order(created_at: :asc) #@sort`が "oldest" と等しい場合、`@post_boards`を`created_at`の昇順でソート
  else
    @post_boards = @community.post_boards.order(created_at: :desc) #特定のコミュニティに関連する掲示板データを取得し、ソートの条件に従って並び替え
  end
  
  @users = User.all

  # 追加コード
  @users = @post_boards.map(&:user).uniq #@post_boards`は特定のコミュニティに関連する掲示板データのリストを表しています。そして、`map`メソッドを使って、`@post_boards`の各要素（つまり各掲示板）に対して以下の処理を実行
  end                                    #&:user`は、各掲示板の`user`というメソッドを呼び出すための短縮記法です。つまり、各掲示板のユーザーを取得
                                         #uniq`メソッドを使って、ユーザーリストから重複したユーザーを除去しています。これにより、`@users`には`@post_boards`に関連するユーザーの一意なリストが代入
  def create
    @community = Community.find(params[:community_id]) # 選択したコミュニティを取得
    @post_boards = @community.post_boards
    @post_board = @community.post_boards.build(post_board_params) #buildメソッド　アソシエーションを使用して、モデルから取得し新しいオブジェクトを作成
    @post_board.user_id = current_user.id
    if @post_board.save
      flash[:notice] = "成功しました。"
      redirect_to community_post_boards_path(@community)
    else
      flash[:alert] = "登録に失敗しました。"
      render :index
    end
  end

    def destoroy
       @post_board = PostBoards.find(params[:id]) # 削除する投稿を取得
    if @post_boad.user_id == current_user.id # ログインユーザーと投稿のユーザーが一致しているかチェック
       @post_board.destroy #投稿削除
    end
       flash[:notice] = "削除しました。"
       redirect_to community_post_boards_path(params[:community_id]) # コミュニティの投稿一覧ページにリダイレクト
    end

    private

    def post_board_params
      params.require(:post_board).permit(:user_id, :community_id, :body,:favorite_id)
    end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :ensure_normal_user, only: :destroy
  
  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
  #特定のユーザー（メールアドレスが 'guest@example.com' の場合）は削除できないことを示すために、リダイレクトとメッセージ表示
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana])
   end

   def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana])
   end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  
def after_sign_up_path_for(resource)
    user_path(current_user.id)
end
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create #@room`という変数に、新しいチャットルームを作成。`Room.create`は、`Room`モデルに新しいレコードを作成するメソッド
    @current_entry = Entry.create(user_id: current_user.id, room_id: @room.id) #@current_entry`という変数に、現在のユーザー (`current_user`) のエントリーを作成
    @another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: @room.id) #Entry`モデルに新しいレコードを作成するメソッドです。このエントリーには、`user_id`として現在のユーザーのID (`current_user.id`) を、`room_id`として先ほど作成したチャットルームのID (`@room.id`) を指定
    redirect_to rooms_path(@room) #@another_entry変数に、`params[:entry][:user_id]`で指定されたユーザーのエントリーを作成。`params[:entry][:user_id]`は、リクエストパラメータの`entry`ハッシュの`user_id`キーの値を取得しています。このエントリーには、`user_id`として指定されたユーザーのID、`room_id`として先ほど作成したチャットルームのIDを指定
  end


  def index
    @current_entries = current_user.entries.order('created_at DESC').page(params[:page]).per(3) #@current_entries変数に、current_userに関連するエントリーのデータを取得
    my_room_id = [] #my_room_id`という空の配列を作成
    @current_entries.each do |entry| #entry.room.id`でエントリーのルームIDを取得し、それを`my_room_id`配列に追加
      my_room_id << entry.room.id #現在のユーザーが関与しているエントリーを取得し、それぞれのエントリーからルームIDを抽出して、`my_room_id`配列に追加
    end
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: @current_user.id)  # 自分のroom_idでuser_idが自分じゃないのを取得
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first #@entries`は、ある特定のコンテキストや条件に関連するエントリーのデータを表しています。コード中の該当箇所では、他の部分で定義されている前提
  end                                                                   #@entries`から、現在のユーザー (`current_user`) のユーザーID (`user_id`) とは異なるエントリーをフィルタリングしています。`.where.not(user_id: current_user.id)`は、`user_id`が現在のユーザーのIDと異なるエントリーを抽出するための条件
end                                                                     #.first`は、フィルタリングされた結果から最初のエントリーを取得するメソッド

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
  @model = params[:model] #params[:model]`、`params[:content]`、`params[:method]`という変数に、検索フォームから送信された値が代入
  @content = params[:content]
  @method = params[:method]

  if @model == 'User'
  @records = User.search_for(@content, @method) #@model`の値に応じて、検索対象となるモデルのクラスメソッドを呼び出す。条件分岐を使って、`@model`が'user'の場合は`User`クラスの`search_for`メソッドを呼び出し、'community'の場合は`Community`クラスの`search_for`メソッドを呼び出し、'post_board'の場合は`PostBoard`クラスの`search_for`メソッドを呼び出す。
  elsif @model == 'Community'
  @records = Community.search_for(@content, @method)
  elsif @model == 'Post_board'
  @records = PostBoard.search_for(@content, @method)
  end
render 'search_results'
  end

 def genre_search
  @genre = Genre.find(params[:id])
  @communities = Community.where(genre_id: @genre.id)
  @genres = Genre.all
  @communities = @genre.communities.order('created_at DESC').page(params[:page]).per(4) #@genreとcommunitesを紐付け検索結果に対してページネーション。
 end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
   before_action :user_state, only: [:create]

def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path
end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

#   protected

#   # アクティブであることを判断する処理
#   def user_state
#   @user = User.find_by(email: params[:user][:email])
#   return if @user.nil?
#   if @user.is_active
#   return unless @user.valid_password?(params[:user][:password])
#   sign_in(@user)
#     redirect_to user_root_path
#   else
#     flash[:notice] = "既に退会済みのアカウントです。新規会員登録が必要になります。"
#     redirect_to new_user_registration_path
#   end
#   end

#admmin側で制限中の場合ログインが出来ない権限

def user_state
    user = User.find_by(email: params[:user][:email])
    if user && user.status != "制限中" # statusが制限中でなければログイン可能
    else
      flash[:notice] = "メールアドレスが登録されていないか、制限中です。新規会員登録が必要です。"
      redirect_to new_session_path
    end
end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/communities_helper.rb
module User::CommunitiesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/views/admin/users/edit.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col">
      <h2 class="mb-4 text-center"><%= @user.name %>さんの会員情報編集</h2>
       <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <div class="d-flex align-items-center pb-3">
         <table class="mt-4">
          <tr>
            <th class="p-2">会員ID</th>
            <td class="pr-5"></td>
            <td class="p-2"><%= @user.id %></td>
          </tr>
          <tr>
            <th class="p-2">氏名</th>
            <td></td>
            <td class="p-2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="p-2">フリガナ</th>
            <td></td>
            <td class="p-2"><%= @user.name_kana %></td>
          </tr>
          <tr>
            <th class="p-2">メールアドレス</th>
            <td></td>
            <td class="p-2"><%= @user.email %></td>
          </tr>
          <tr>
            <th class="p-2">会員ステータス</th>
            <td></td>
            <th class="p-2"><%= f.radio_button :is_active, "false" %>有効</th>
            <th class="p-2"><%= f.radio_button :is_active, "true" %>制限中</th>
          </tr>
          <tr>
            <th class="p-2"></th>
            <td></td>
            <th class="p-2"><%= f.submit "変更を保存", class: "btn btn-success" %></th>
          </tr>
         </table>
        </div>
      <% end %>
    </div>
  </div>
</div>
<style>
  body {
  background-color: #FFFFF0; /* 背景色の指定 */
  }
</style>

app/views/admin/users/index.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col">
      <h2 class="mb-4 text-center">会員一覧</h2>
        <table class="table table-bordered">
         <thead style="background-color: #e9ecef;">
          <tr>
            <th>会員ID</th>
            <th>アイコン</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="align-middle"><%= user.id %></td>
            <td class="align-middle"><%= image_tag user.get_profile_image(100, 100), class: "rounded-circle mx-auto d-block" %></td>
            <td class="align-middle"><%=link_to user.name, admin_user_path(user.id) %></td>
            <td class="align-middle"><%= user.email %></td>
            <td class="<%= user.status == '有効' ? 'text-warning' : 'text-success' %>"><%= user.status %></td>
            </tr>
              <% end %>
              </tbody>
             </table>
           <div class="d-flex justify-content-center">
          </div>
        </div>
       </div>
      </div>
     <div class="users_paginate">
   <%= paginate @users %>
  </div>
 <head>
<style>
  body {
  background-color: #FFFFF0; /* 背景色の指定 */
  }
.users_paginate{
  width: 100%;
  margin: auto;
}

/* ページネーション全体 */
.pagination{
  text-align: center;
  display: flex;
  justify-content: center; 
}

/* ページネーションのspan */
.pagination span{
  text-align: center;
  width: 50px;
  font-size: 20px;
}

/* ページネーションのリンク文字（a） */
.pagination a{
  color: #818181;
  display: block;
  width: 100%;
  height: 115%;
  font-weight: bold;
  padding: 10px;
}

/* ページネーションの文字にカーソルを載せた時 */
.pagination a:hover{
  width: 60px;
  height: 60px;
  background-color: #84b8eb;
  color: #FFF;
  border-radius: 100%;
  padding: 10px;
}

/* 現在のページの数字についての表記 */
.current{
  font-weight: bold;
  color: #84b8eb;
  padding: 10px;
}
  </style>

app/views/admin/users/show.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col">
      <h2 class="mb-4 text-center"><%= @user.name %>さんの会員詳細</h5>
        <div class="d-flex align-items-center pb-3">
         <table class="mt-4">
          <tr>
            <th class="p-2">会員ID</th>
            <td class="pr-5"></td>
            <td class="p-2"><%= @user.id %></td>
          </tr>
          <tr>
            <th class="p-2">アイコン</th>
            <td class="pr-5"></td>
            <td class="p-2"><%= image_tag @user.get_profile_image(100, 100) %></td>
          </tr>
          <tr>
            <th class="p-2">氏名</th>
            <td></td>
            <td class="p-2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="p-2">フリガナ</th>
            <td></td>
            <td class="p-2"><%= @user.name_kana %></td>
          </tr>
          <tr>
            <th class="p-2">メールアドレス</th>
            <td></td>
            <td class="p-2"><%= @user.email %></td>
          </tr>
          <tr>
            <th class="p-2">会員ステータス</th>
            <td></td>
              <% if @user.is_active %>
              <th class=”text-success p-2>制限中</th>
  　　　　　　　　　　<% else %>
             <th class="text-secondary p-2">有効</th>
              <% end %>
          </tr>
          <tr>
            <th></th>
            <td></td>
            <td class="pt-4">
              <span class="pr-5"><%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success" %></span>
              <%= link_to "詳細ページへ", admin_users_path(@user), class: "btn btn-primary" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<style>
  body {
  background-color: #FFFFF0; /* 背景色の指定 */
  }
</style>